### ISSUE TITLE
Security problem with commands in README.md

### ISSUE THREAD

**Issue by shaaati** [dustyfresh/OnionIRC#1]
1024 bit RSA keys are definitely not what one would want when setting up a Tor Hidden Service.
You should update the readme to at least 2048 bits, although 4096 probably wouldn't hurt either.

**Comment by dustyfresh** [comment]
shaaati Thank you for pointing this out! I forgot to update the key size as I lowered it since my dev work was done on my raspberry pi. The readme has been updated.
